### ISSUE TITLE
Should running datagetter.py with no args give help and exit?

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/datagetter#3]
I feel like if I have a tool I don't know how to use, running it with no options is generally a safe and quick thing to do, and I generally expect it to just give me some output that tells me what it is or how to use it (with the exception of basic tools like `cat`, etc)

**Comment by michaelwood** [comment]
I think as this doesn't do anything destructive and can be cancelled via ctrl+c that it is fine that it starts doing things on execution. This is generally the norm unless a command positional arguments which we currently don't have. At the moment it is also useful keep compatibility with the old datagetter behaviour.

**Comment by michaelwood** [comment]
Tidying up old issues. Feel free to re-open if this is important.
